{{- range $key, $spec := .Values }}
{{- if and (ne $key "enabled") }}
{{- if $spec.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ $key }}-{{ $.Release.Namespace }}
  labels:
    app: {{ template "gateway.name" $ }}
    chart: {{ template "gateway.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
rules:
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules", "gateways"]
  verbs: ["get", "watch", "list", "update"]
---
{{- end }}
{{- end }}
{{- end }}
