dependencies:
  - name: sidecarInjectorWebhook
    version: 1.1.0
    condition: sidecarInjectorWebhook.enabled
    repository: file://../subcharts/sidecarInjectorWebhook
  - name: security
    version: 1.1.0
    condition: security.enabled
    repository: file://../subcharts/security
